[build]
functions = "functions"
[[redirects]]
 from = "https://jolly-dango-f4d24a.netlify.app/web-data"
  to = "/.netlify/functions/api"
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept" }
  methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  status = 200
  force = true