[build]
functions = "functions"
[[redirects]]
 from = "/jolly-dango-f4d24a.netlify.app/web-data"
  to = "/.netlify/functions/api"
  status = 200

[[headers]]
for = "/*"
   [headers.values]
   Access-Control-Allow-Origin = "*"
   Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
